import { MdOutlineEmail, MdDateRange } from "react-icons/md";

// ✅ Just export a normal array (NO useState here!)
export const bwpstAryData = [
  {
    id: 1,
    name: "Get Free Ticket",
    email: <MdOutlineEmail />,
    selectedCampaign: "Whatsapp Campaign",
    target: "all",
    calender: <MdDateRange />,
    date1: "2023-12-01",
    date2: "2023-12-31",
    sentVAlue: "0",
    resValue: "0",
    status: "active",
  },
  {
    id: 2,
    name: "Best Offers for Our Customer",
    email: <MdOutlineEmail />,
    selectedCampaign: "Whatsapp Campaign",
    target: "all",
    calender: <MdDateRange />,
    date1: "2023-12-01",
    date2: "2023-12-31",
    sentVAlue: "0",
    resValue: "0",
    status: "draft",
  },
  {
    id: 3,
    name: "Journey Towards Dreams",
    email: <MdOutlineEmail />,
    selectedCampaign: "Whatsapp Campaign",
    target: "all",
    calender: <MdDateRange />,
    date1: "2023-12-01",
    date2: "2023-12-31",
    sentVAlue: "0",
    resValue: "0",
    status: "scheduled",
  },
  {
    id: 4,
    name: "Journey Towards Dreams",
    email: <MdOutlineEmail />,
    selectedCampaign: "Whatsapp Campaign",
    target: "all",
    calender: <MdDateRange />,
    date1: "2023-12-01",
    date2: "2023-12-31",
    sentVAlue: "0",
    resValue: "0",
    status: "scheduled",
  },
  {
    id: 5,
    name: "Journey Towards Dreams",
    email: <MdOutlineEmail />,
    selectedCampaign: "Whatsapp Campaign",
    target: "all",
    calender: <MdDateRange />,
    date1: "2023-12-01",
    date2: "2023-12-31",
    sentVAlue: "0",
    resValue: "0",
    status: "scheduled",
  },
  {
    id: 6,
    name: "Journey Towards Dreams",
    email: <MdOutlineEmail />,
    selectedCampaign: "Whatsapp Campaign",
    target: "all",
    calender: <MdDateRange />,
    date1: "2023-12-01",
    date2: "2023-12-31",
    sentVAlue: "0",
    resValue: "0",
    status: "scheduled",
  },
];


export const multnCmpnAry = [
  {
    id: 1,
    name: "MUltan Free Ticket",
    email: <MdOutlineEmail />,
    selectedCampaign: "Whatsapp Campaign",
    target: "all",
    calender: <MdDateRange />,
    date1: "2023-12-01",
    date2: "2023-12-31",
    sentVAlue: "0",
    resValue: "10",
    status: "active",
  },
  {
    id: 2,
    name: "Best Offers ",
    email: <MdOutlineEmail />,
    selectedCampaign: "Whatsapp Campaign",
    target: "all",
    calender: <MdDateRange />,
    date1: "2023-12-01",
    date2: "2023-12-31",
    sentVAlue: "0",
    resValue: "0",
    status: "draft",
  },
  {
    id: 3,
    name: "Journey Towards Goals",
    email: <MdOutlineEmail />,
    selectedCampaign: "Whatsapp Campaign",
    target: "all",
    calender: <MdDateRange />,
    date1: "2023-12-01",
    date2: "2023-12-31",
    sentVAlue: "0",
    resValue: "0",
    status: "scheduled",
  },
  {
    id: 4,
    name: "Hi ",
    email: <MdOutlineEmail />,
    selectedCampaign: "Whatsapp Campaign",
    target: "all",
    calender: <MdDateRange />,
    date1: "2023-12-01",
    date2: "2023-12-31",
    sentVAlue: "0",
    resValue: "0",
    status: "scheduled",
  },
  {
    id: 5,
    name: "NO Body KNow",
    email: <MdOutlineEmail />,
    selectedCampaign: "Whatsapp Campaign",
    target: "all",
    calender: <MdDateRange />,
    date1: "2023-12-01",
    date2: "2023-12-31",
    sentVAlue: "0",
    resValue: "0",
    status: "scheduled",
  },
  {
    id: 6,
    name: "Journey Model ",
    email: <MdOutlineEmail />,
    selectedCampaign: "Whatsapp Campaign",
    target: "all",
    calender: <MdDateRange />,
    date1: "2023-12-01",
    date2: "2023-12-31",
    sentVAlue: "0",
    resValue: "0",
    status: "scheduled",
  },
];
