// SuperCampnArray.js (updated)
import { MdOutlineEmail, MdDateRange } from "react-icons/md";

export const campaignData = [
  {
    city: "bahawalpur",
    Elements: [
      {
        id: 1,
        name: "Get Free Ticket",
        email: <MdOutlineEmail />,
        selectedCampaign: "Whatsapp Campaign",
        target: "all",
        calender: <MdDateRange />,
        date1: "2023-12-01",
        date2: "2023-12-31",
        sentVAlue: "0",
        resValue: "0",
        status: "active",
      },
      // {
      //   id: 2,
      //   name: "Email Promotion",
      //   email: <MdOutlineEmail />,
      //   selectedCampaign: "Email Campaign",
      //   target: "students",
      //   calender: <MdDateRange />,
      //   date1: "2023-11-01",
      //   date2: "2023-11-30",
      //   sentVAlue: "0",
      //   resValue: "0",
      //   status: "draft",
      // },
      // {
      //   id: 3,
      //   name: "Station Services",
      //   email: <MdOutlineEmail />,
      //   selectedCampaign: "Email Campaign",
      //   target: "students",
      //   calender: <MdDateRange />,
      //   date1: "2023-11-01",
      //   date2: "2023-11-30",
      //   sentVAlue: "0",
      //   resValue: "0",
      //   status: "completed",
      // },
      // {
      //   id: 4,
      //   name: "Staion Requirements",
      //   email: <MdOutlineEmail />,
      //   selectedCampaign: "Email Campaign",
      //   target: "students",
      //   calender: <MdDateRange />,
      //   date1: "2023-11-01",
      //   date2: "2023-11-30",
      //   sentVAlue: "0",
      //   resValue: "0",
      //   status: "active",
      // },
    ]
  },
  {
    city: "multan",
    Elements: [
      {
        id: 1,
        name: "Multan Free Ticket",
        email: <MdOutlineEmail />,
        selectedCampaign: "Whatsapp Campaign",
        target: "all",
        calender: <MdDateRange />,
        date1: "2023-12-01",
        date2: "2023-12-31",
        sentVAlue: "0",
        resValue: "10",
        status: "active",
      },
      // {
      //   id: 2,
      //   name: "Multan New Offer",
      //   email: <MdOutlineEmail />,
      //   selectedCampaign: "Whatsapp Campaign",
      //   target: "all",
      //   calender: <MdDateRange />,
      //   date1: "2023-12-01",
      //   date2: "2023-12-31",
      //   sentVAlue: "0",
      //   resValue: "10",
      //   status: "completed",
      // },
      // {
      //   id: 3,
      //   name: "Multan Free Ticket",
      //   email: <MdOutlineEmail />,
      //   selectedCampaign: "Whatsapp Campaign",
      //   target: "all",
      //   calender: <MdDateRange />,
      //   date1: "2023-12-01",
      //   date2: "2023-12-31",
      //   sentVAlue: "0",
      //   resValue: "10",
      //   status: "active",
      // },
      // {
      //   id: 4,
      //   name: "Multan ByPass Services",
      //   email: <MdOutlineEmail />,
      //   selectedCampaign: "Email Campaign",
      //   target: "customers",
      //   calender: <MdDateRange />,
      //   date1: "2023-11-15",
      //   date2: "2023-12-15",
      //   sentVAlue: "0",
      //   resValue: "5",
      //   status: "draft",
      // },
    ]
  }
];